config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  
  resources :states do
    resources :counties do
      resources :cities
    end
  end

  root to: 'accounts#index'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ApplicationRecord
  belongs_to :city, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string
#  county_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ApplicationRecord
  has_many :accounts
  belongs_to :county, optional: true
  scope :alpha_asc, -> { order(name: :asc) }
  scope :select_collection, -> { alpha_asc.map { |s| [s.name, s.id] } }
end

app/models/county.rb
# == Schema Information
#
# Table name: counties
#
#  id         :integer          not null, primary key
#  name       :string
#  state_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class County < ApplicationRecord
  belongs_to :state
  has_many :cities
  scope :alpha_asc, -> { order(name: :asc) }
  scope :select_collection, -> { alpha_asc.map_array }
  scope :map_array, lambda {
    map { |s| [s.name, s.id, { url: cities_path(s.state_id, s.id) }] }
  }

  scope :cities_path, lambda { |state_id, county_id|
    Rails.application.routes.url_helpers.state_county_cities_path(
      state_id: state_id,
      county_id: county_id
    )
  }
end

app/models/state.rb
# == Schema Information
#
# Table name: states
#
#  id         :integer          not null, primary key
#  name       :string(50)
#  abbr       :string(2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class State < ApplicationRecord
  has_many :counties
  scope :alpha_asc, -> { order(name: :asc) }
  scope :select_collection, -> { alpha_asc.map { |s| [
    s.name, 
    s.id, 
    { url: Rails.application.routes.url_helpers.state_counties_path(s) }] }}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all
  end

  def show
  end

  def new
    @account = Account.new
  end

  def edit
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :city_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    state = State.find(params[:state_id])
    county = state.counties.find(params[:county_id])
    cities = county.cities
    render json: cities.select_collection
  end
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  def index
    @state = State.find(params[:state_id])
    @counties = @state.counties
    render json: @counties.select_collection
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div data-controller='city-selector'>
    <div class="field">
      <%= form.label :state_id %>
      <%= form.select :state_id, 
                      State.select_collection, 
                      { include_blank: true }, 
                      { 
                        class: 'form-control', 
                        data: { 
                          target: 'city-selector.state_input', 
                          action: 'city-selector#state_changed' }} %>
    </div>

    <div class="field">
      <%= form.label :county_id %>
      <%= form.select :county_id, [], {}, { 
        class: 'form-control',
        data: {
          target: 'city-selector.county_input',
          action: 'city-selector#county_changed'
        }} %>
    </div>

    <div class="field">
      <%= form.label :city_id %>
      <%= form.select :city_id, [], {}, { 
        class: 'form-control',
        data: {
          target: 'city-selector.city_input',
          city_id: account&.city&.id,
          county_id: account&.city&.county&.id,
          state_id: account&.city&.county&.state&.id
        }} %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.city&.name %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @account.city&.name %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>